apiVersion: v1
kind: Template
labels:
  template: selinon-api-deploymentconfig
  selinon: 1.0.0
metadata:
  name: selinon-api-deploymentconfig
  annotations:
    description: Selinon API
    openshift.io/display-name: 'Selinon: API'
    version: 1.0.0
    tags: poc,selinon,api
    template.openshift.io/documentation-url: https://github.com/selinon/
    template.openshift.io/long-description: Selinon API deployment configuration template.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: selinon-api
    labels:
      app: selinon
      component: selinon-api
  spec:
    to:
      kind: Service
      name: selinon-api

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: selinon-api
      app: selinon
      component: selinon-api
    name: selinon-api
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      service: selinon-api


- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: selinon-api
      app: selinon
      component: selinon-api
    name: selinon-api
  spec:
    replicas: 1
    selector:
      service: selinon-api
    template:
      metadata:
        labels:
          service: selinon-api
      spec:
        containers:
        - env:
          - name: BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: selinon
                key: broker-url
          name: selinon-api
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            # TODO: create liveness
            httpGet:
              path: '/'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - selinon-api
        from:
          kind: ImageStreamTag
          name: 'selinon-api:latest'
